# .streamlit/secrets.toml

PROVERBS_SHEET_NAME = "WisdomJotter_Proverbs"
LIFE_LESSONS_SHEET_NAME = "WisdomJotter_LifeLessons"

[gcp_service_account]
type = "service_account"
project_id = "wisdomjotter-sheets-app-467410"
private_key_id = "f28632ce0c1006ce478a6103a0faa0bbcb96e914"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCxDbXKRSmS1yL2
xJ+JOaMkIOF8RDW4XDvIKykCJlWsnbHo+TtpHNNTMCjHsebY6sENFjT1xFn0IODS
STmI1UQ7yvhs2avRZ3szRqDpdTZ+1zL8uL9nITzIFKKRDl6CE4XXLC4P6U8twF8y
jtwPtPiueNNelmE49E2eR6grKFDNd279qLQOvCcFkVI7B9U13UjsZSPYI1qJtBvW
DVkiCuW0Urs7KpXG12HaLCSduxhYlFbrx/Lrzae42NXnobwPC9kRkuhnrU4dpCh5
cmvLYjxU3AR8VLQN1kS/lNbjTfDbm4C66vqYwzMgrUDQeOfUA885ChYgN0d0imuL
QCDaohu3AgMBAAECggEAMcXIZpHV05VOG2//50xAK/5gVRY5wdeP6MAVWajcKdf0
9SjnRi/Xyol91VGSM0WfOqYVAkgN/56khQkXtvs5INP4zWTNs+Ly0+HVh3uvc63c
hAYNrJi/5QFECCIxeECzvd8KHef5HcP4HxbhDztRM3788Ji2wROQpF/Bi0xclr22
TN+b2gNe7rAbEjgaJhqTrqgak1VWM0/7U2TX/EmTyh62bD6o0yWKO2DptDE5msXB
aSPxYUQqnVK+zn1//kL9XNVQIDbC/ybV6n/JBH076k7J8t89Iky1HCE7aVxcy/0Z
N9ufCGQUBBF2UzSdKzyXZSXirR+ngyzwbnPZzPoKeQKBgQDXjHbb1bWahBxO24TD
lXrXEsdFBX5fLbmvK6Jonqjcv/lh3p93wNOPkDkZkFF/FWF36+ZvD+RZPWo6oLXV
IBX5c586INHdOy9NWYHueN9z+ixIkHwXGrSotShl6r+3qcmLW0k2u3XXKF/AoyIl
s+HPW2eQOZQNr9LaVTfiUYmHOQKBgQDSR9YsmaoOOXN88EOKmJmcrdevfUepHGea
12wYMH1b6BtzrgY4wPiYgaPE9MNizo58uDQ9jYjHENC9gwOvIhv5AZQmszNMSRw8
3df4lzLi0TerDp3UNfaB8M9QDTpbLXjtruEGY1WtSH4oFB6qLA7tJT2I02UcnlM0
+4dx/DpKbwKBgCtUKxhpz0WuRNp9OiTuyXCub6wqPIr5cBgMV2tcaWlmlcTcsYWr
F1wGi9PdtOQs8hjfLMUqlqZxuAbtA2BCQOiSG3Hd4xHrsciEs5+yYIi5w2ka0jb6
wVIgiGxkUgGjecYvpXoBGOEVVpossNKPZFcAcsMFMAPIUkRdWQx/g3vRAoGBALNl
5isWziZkjUrCEF1l42fwSFrHnyN/wEQyFV5twAVw+Dqw9U3mFDDIKVgXGbpqTtXI
sYjx/wcWKYAFDleT2hmOZz69E765gQXMnjzPgfJQXBXr2mr5vt0M/VFmd6riGJFu
6Tvx815qwnae86pq/DEF3IGnGFRaHtLM5LkyXuixAoGAG9B20PYKnd6psT9qugmK
yPuNq/MMMggIhIoMhaM3mRYXdOEprjc1xLVzER6Cuobl2aBfHYsPKHs0tLyNhn/I
e6nnOlfq8dlIfxYK/rLhwNuSLbcWwLHvDdXERaAuy+Wil79eLYBnZ763aPwveLCU
rbWSvuRS0r7kjGH09hnEdeI=
-----END PRIVATE KEY-----"""
client_email = "streamlit-sheets-connector@wisdomjotter-sheets-app-467410.iam.gserviceaccount.com"
client_id = "104184848000653286613"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets-connector%40wisdomjotter-sheets-app-467410.iam.gserviceaccount.com"
universe_domain = "googleapis.com"



